//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Composition {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Localization {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Localization() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("Composition.Localization", typeof(Localization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string Load_File_Message {
            get {
                return ResourceManager.GetString("Load_File_Message", resourceCulture);
            }
        }
        
        internal static string Skip_File_Message {
            get {
                return ResourceManager.GetString("Skip_File_Message", resourceCulture);
            }
        }
        
        internal static string Import_Fragment_Button {
            get {
                return ResourceManager.GetString("Import_Fragment_Button", resourceCulture);
            }
        }
        
        internal static string Export_Button {
            get {
                return ResourceManager.GetString("Export_Button", resourceCulture);
            }
        }
        
        internal static string Import_Folder_Button {
            get {
                return ResourceManager.GetString("Import_Folder_Button", resourceCulture);
            }
        }
        
        internal static string Dialog_Import {
            get {
                return ResourceManager.GetString("Dialog_Import", resourceCulture);
            }
        }
        
        internal static string Dialog_Cancel {
            get {
                return ResourceManager.GetString("Dialog_Cancel", resourceCulture);
            }
        }
        
        internal static string File_Filter_Description {
            get {
                return ResourceManager.GetString("File_Filter_Description", resourceCulture);
            }
        }
        
        internal static string Dialog_Export {
            get {
                return ResourceManager.GetString("Dialog_Export", resourceCulture);
            }
        }
    }
}
